version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: modularization_db  # Must match the service name below
      DB_PORT: 5432
      DB_DATABASE: jouleslabdb
      DB_USERNAME: postgres
      DB_PASSWORD: antu
      REDIS_HOST: redis     # Add Redis host env var
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: modularization_db  # Add this if you need this specific name
    environment:
      POSTGRES_DB: jouleslabdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: antu
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: